{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
{{- range .Values.ingress.tls -}}
{{- if or .crt .key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
type: kubernetes.io/tls
data:
 {{ if .crt -}}
  tls.crt: {{ .crt }}
 {{- end }}
 {{ if .key -}}
  tls.key: {{ .key }}
 {{- end }}
---
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
